---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: default
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
  # change the monitors to match your IP addresses of your ceph mon nodes
  #ip-172-31-26-100.ec2.internal   Ready     <none>    1h        v1.11.3
  #ip-172-31-42-231.ec2.internal   Ready     <none>    1h        v1.11.3
  #ip-172-31-73-203.ec2.internal   Ready     <none>    1h        v
  monitors: 172.31.26.100:6789,172.31.42.231:6789,172.31.73.203:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: default
  pool: rbd
  userId: admin
  userSecretName: ceph-secret
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
