---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: default
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
  # change the monitors to match your IP addresses of your ceph mon nodes
  monitors: 172.31.10.198:6789,172.31.21.183:6789,172.31.43.148:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: default
  pool: rbd
  userId: admin
  userSecretName: ceph-secret
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
